/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForkliftForRentInDelhiIndexRouteImport } from './routes/forklift-for-rent-in-delhi/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForkliftForRentInDelhiIndexRoute =
  ForkliftForRentInDelhiIndexRouteImport.update({
    id: '/forklift-for-rent-in-delhi/',
    path: '/forklift-for-rent-in-delhi/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forklift-for-rent-in-delhi/': typeof ForkliftForRentInDelhiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forklift-for-rent-in-delhi': typeof ForkliftForRentInDelhiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forklift-for-rent-in-delhi/': typeof ForkliftForRentInDelhiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forklift-for-rent-in-delhi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forklift-for-rent-in-delhi'
  id: '__root__' | '/' | '/forklift-for-rent-in-delhi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForkliftForRentInDelhiIndexRoute: typeof ForkliftForRentInDelhiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forklift-for-rent-in-delhi/': {
      id: '/forklift-for-rent-in-delhi/'
      path: '/forklift-for-rent-in-delhi'
      fullPath: '/forklift-for-rent-in-delhi/'
      preLoaderRoute: typeof ForkliftForRentInDelhiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForkliftForRentInDelhiIndexRoute: ForkliftForRentInDelhiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
